solana:
    read_rpcs:
        -   url: https://api.devnet.solana.com
            ratelimit: 4 # requests per second
    write_rpcs:
        -   url: https://api.devnet.solana.com
            ratelimit: 4 # requests per second
    reader_concurrency: 32

ssl:
    key: "key.pem"
    cert: "cert.pem"
