[package]
name = "smt-circom"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.5"
heapless = "0.9"
light-poseidon = "0.4"
rocksdb = { version = "0.24", default-features = false, optional = true }
thiserror = "2"

[features]
default = ["rocksdb", "rocksdb/bindgen-runtime"]
